import { AboutModel } from "@/components/AboutModel";

export default function AboutPage() {
  return (
    <div className="space-y-8">
      <section className="space-y-3">
        <h1 className="text-3xl font-bold text-white">About This Site</h1>
        <p className="max-w-3xl leading-relaxed text-[var(--muted)]">
          Sports Picks Blog publishes daily MLB betting picks generated by two in-house
          projection systems: a Random Forest moneyline model and a player props edge engine.
          Picks are synced each morning via a Python export script — no manual curation.
        </p>
      </section>

      <AboutModel />

      <section className="space-y-4 rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-6">
        <h2 className="text-xl font-semibold text-white">Moneyline Model</h2>
        <p className="leading-relaxed text-[var(--muted)]">
          The moneyline system trains Random Forest regressors on MLB game data to predict home
          and away runs, then derives win probabilities. It flags games where the model&apos;s
          implied probability exceeds the market by more than 3%, sizing plays with quarter-Kelly.
        </p>
        <ul className="list-disc space-y-2 pl-5 text-[var(--muted)]">
          <li>Data: MLB Stats API, Open-Meteo weather, rolling team form</li>
          <li>Output: ranked value picks with edge % and suggested bankroll sizing</li>
          <li>Backtest: 600-game rolling window with ROI and Brier score tracking</li>
        </ul>
      </section>

      <section className="space-y-4 rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-6">
        <h2 className="text-xl font-semibold text-white">Player Props Model</h2>
        <p className="leading-relaxed text-[var(--muted)]">
          The props system projects batter total bases and pitcher outs using base rates,
          matchup adjustments, park factors, and live market lines. Top conviction plays are
          ranked by absolute edge percentage across both markets.
        </p>
        <ul className="list-disc space-y-2 pl-5 text-[var(--muted)]">
          <li>Markets: batter total bases, pitcher outs</li>
          <li>Data: MLB lineups, Statcast, TheRundown / The Odds API</li>
          <li>Output: conviction table plus full batter and pitcher edge sheets</li>
        </ul>
      </section>

      <section className="space-y-4 rounded-xl border border-[var(--card-border)] bg-[var(--card)] p-6">
        <h2 className="text-xl font-semibold text-white">How to Sync Picks</h2>
        <pre className="overflow-x-auto rounded-lg bg-black/30 p-4 text-sm text-[var(--muted)]">
{`# Configure paths in .env.local, then:
npm run sync-picks

# Start the site locally:
npm run dev`}
        </pre>
      </section>

      <section className="space-y-4 rounded-xl border border-red-900/50 bg-red-950/20 p-6">
        <h2 className="text-xl font-semibold text-white">Responsible Gambling Disclaimer</h2>
        <p className="leading-relaxed text-[var(--muted)]">
          This site is for entertainment and informational purposes only. Nothing published here
          constitutes financial, legal, or betting advice. Past model performance does not
          guarantee future results. Sports betting involves risk of financial loss.
        </p>
        <p className="leading-relaxed text-[var(--muted)]">
          Only wager what you can afford to lose. If you or someone you know has a gambling
          problem, call{" "}
          <strong className="text-white">1-800-GAMBLER</strong> (1-800-426-2537) or visit{" "}
          <a
            href="https://www.ncpgambling.org"
            className="text-[var(--accent)] hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            ncpgambling.org
          </a>
          .
        </p>
        <p className="leading-relaxed text-[var(--muted)]">
          You must be of legal gambling age in your jurisdiction to place bets. Verify local
          laws before participating in any form of sports wagering.
        </p>
      </section>
    </div>
  );
}
